#!/usr/bin/env python3
import os
from sys import argv

bell_mp3 = "/".join(argv[0].split("/")[:-1]) +"/bell.mp3"

if len(argv)<2:
    print(f"Usage: {argv[0]} how-many-segments optional:starting-segment")
    exit()
num_segments = int(argv[1])
if len(argv)>2:
    start_segment=int(argv[2])
else:
    start_segment = 1
while True:
    to_play = ""
    for i in range(start_segment,start_segment+num_segments):
        to_play += str(i).zfill(2)+".mp3 "
    start_segment += num_segments
    os.system(f"vlc --play-and-exit {to_play} {bell_mp3}")
    print("Just played:", to_play, "\n")
    ans = input("q to quit, -# to repeat, or Enter to continue> ")
    if ans=="q": exit()
    if len(ans):
        if ans[0]=="-":
            start_segment -= int(ans[1])


