#!/usr/bin/env python3
import os, glob, sys, Mp3
from sys import argv

sourceDir = "."
targetDir = "splitedFiles"
if len(argv)>1:
    targetDir = argv[1]
print("   Target dir is", targetDir)

if not os.path.isdir(targetDir):
    print("   Creating target dir")
    os.mkdir(targetDir)
if not os.path.isdir(targetDir):
    print("Could not create the target dir '"+ sourceDir +"' - Aborting.")
    exit()
    
mp3 = Mp3.Mp3(sourceDir, targetDir, True)

fns = [ os.path.basename(fn) for fn in glob.glob( os.path.join(sourceDir, "*.mp3") ) ]

fns.sort(key=mp3.sort_numericaly_a_list_of_mixed_strings)
startFileNum = 1


for fn in fns:
    print("fn",fn,"startFileNum",startFileNum)
    numFiles = mp3.splitFile(fn, 15*60, startFileNum)
    print("    Splited the file '"+ fn +"' into %d parts." % numFiles)
    startFileNum += numFiles
